### ISSUE TITLE
Buffer causes a Content Security Policy violation on some sites without actually activating the extension

### ISSUE THREAD

**Issue by joeyespo** [bufferapp/buffer-extension-shared#50]
Specifically, `tpc-check.html` is violating my the Content Security Policy on localhost. Is there any way to defer this cookie check until the Buffer button is actually pressed? It's muddying up the console when debugging applications.

It's also a little unnerving to have an extension inject iframes to _all_ websites I visit instead of waiting until I activate Buffer.

**Comment by DonnchaC** [comment]
I'm noticing the same issue which is resulting in a huge number of CSP reports being generated.

**Comment by pioul** [comment]
Thanks for the report, and sorry about the radio silence for almost two years – we need to do better!
We haven't changed the inject-in-all-pages behavior, but the good news is that tpc-check.html shouldn't cause CSP violations anymore from v3.2.0 onward :) Hope that helps a little!
