### ISSUE TITLE
If selected content includes quotation marks, don't add additional ones

### ISSUE THREAD

**Issue by tommoor** [bufferapp/buffer-extension-shared#54]
A little-big-detail, screenshot example from the composer:

![image](https://cloud.githubusercontent.com/assets/380914/8664209/019b84c2-2989-11e5-8025-d9b8330a6a9a.png)

**Comment by joelg** [comment]
Great one @tommoor, love that idea. cc @pioul

**Comment by pioul** [comment]
Great idea! I'll go ahead and implement that.
