### ISSUE TITLE
Some markup issue with twitter

### ISSUE THREAD

**Issue by vijayrawatsan** [bufferapp/buffer-extension-shared#58]
<img width="603" alt="screen shot 2015-08-11 at 9 17 03 am" src="https://cloud.githubusercontent.com/assets/985228/9189707/03a13bc6-400a-11e5-9848-bbaa8b021bf1.png">

**Comment by pioul** [comment]
Hey, thanks for bringing this to our attention!

We've released a fix today to make our buttons work great with Twitter again, so you should get an amazing experience again very soon! (Depending on which browser you're using, it could range from a couple of hours for Chrome, Safari and Opera to a bit longer for Firefox.)

Sorry for the temporarily broken situation here :) Thanks again for the help, and please let us know if you see anything else amiss in the future!
