### ISSUE TITLE
[Suspected] Buffer Chrome Extension file vulnerability

### ISSUE THREAD

**Issue by KoozaiDev** [bufferapp/buffer-extension-shared#64]
Hi,

I don't want to raise alarm bells, but i think you may have a vulnerability in a specific file: **buffer-hover-icon@1x.png**

We are noticing a number of users are seeing an injected iframe ad application being driven by a Russian collection of traffic generating sites and they all look to be using the following buffer extension file [buffer-hover-icon@1x.png] as the entry point.

Maybe worth investigating?

`<span id="buffer-extension-hover-button" style="display: none;position: absolute;z-index: 8675309;width: 100px;height: 25px;background-image: url(chrome-extension://noojglkidnpfjbincgijbaiedldjfbhh/data/shared/img/buffer-hover-icon@1x.png);background-size: 100px 25px;opacity: 0.9;cursor: pointer;"></span>`

This is the inner <iframe> being injected, and also not good as it renders the current URL which is not good to those not in the know.

I have tracked down a number of URLs being used to run the application but there are many being used to relay the same output in case of one being closed down.

so far i have traced them back to the following 2 sources, but time is not available to keep digging.

http://rmbn.net/
http://gnezdo.ru

Replacing that file should remove their entry point.

**Collected URLs:**
http://rmbn.net/
http://gnezdo.ru (Linked to a single individual located in Moscow)
http://xlog.info/ (Hiding the embed frames content wrapper)
 http://tredman.com/  (Another frame holder generator)

but all pointing at the same file for entry point to inject their iframe for the ad engine.

See attached images for more details.

Hopefully we can resolve this vulnerability ASAP.

![buffer vulnarbility - scenrio](https://cloud.githubusercontent.com/assets/20998121/20182501/e148c55e-a759-11e6-8c7b-1d8b3854f8a1.jpg)
![buffer vulnarbility](https://cloud.githubusercontent.com/assets/20998121/20182500/e147972e-a759-11e6-9c57-5d09eab937d4.jpg)
)

**Comment by pioul** [comment]
Thanks for reaching out and sharing those concerns!

I'm eager to make sure that the Buffer Extension isn't making possible anything of the sort.

Looking at the screenshot above, both `iframe#buffer_tpc_check` and the span/image `#buffer-extension-hover-button` are elements that we expect our extension to inject in web pages to provide some of the extensions' functionalities: the iframe is used to detect if third-party cookies are allowed in the browser for login purposes, the image is used to display a Buffer Button when hovering on top of images like this one:

<img src="https://cloud.githubusercontent.com/assets/2307365/20225455/c5924778-a843-11e6-9784-4f3701574f67.png" width="234"/>

At first sight, I'm not sure the Buffer Extension has anything to do with those unfortunate ads.

I'd love to help pinpoint the cause of those ads appearing where they shouldn't: could you share a few urls where such ads seem to appear? I visited those above but couldn't see any ads there.

Would you also be up for disabling the Buffer Extension entirely, and visiting those sites again? Do the ads still appear when the Buffer Extension is out of the equation?

Thanks!

**Comment by KoozaiDev** [comment]
Hi @pioul,

Thanks for the reply, i get that the code you are seeing should be included but this is being called / generated from the lower two URL's mentioned above and injected from this source instead.

**(Use a VM instance to view to avoid risks)**
[http://xlog.info/](http://xlog.info/) (Hiding the embed frames content wrapper)
[http://tredman.com/](http://tredman.com/) (Another frame holder generator)

They look to be using a little JS magic to inject this so that they can mimic the same HTML output, I could be wrong, i'm no injection or cross domain injection specialist by any means but just from working back through the rendered code that's what i see.

**URL Samples:**
As for URL's, its not specific it has been happening far and between and hence the limited number of screenshots, but we are seeing this more when looking at [http://resourceguruapp.com/](http://resourceguruapp.com/) or in the case of the screenshots above we where simply visiting a clients website and the same happened again, it injects the "active / visited" URL as part of the title which is again all being done by the JS I have tracked back on the above URL's.

**Disable Buffer Extension:**
I have personally installed the extension to try to scenario test and replicate what our users are seeing.

The issue we are seeing is not happening on every visit, its sporadic so harder to pinpoint exact frequency, I suspect they are using .rand() in regards to the firing.

The 2 members of staff that have seen this, I have asked them to disable buffer and see if it occurs again and to pause on the screen / session  so i can do some more debugging / digging if it does re-appear.

As soon as i have any update around this i will pass this across.

Again, thanks for the reply.

**Comment by pioul** [comment]
Thanks for the additional info! I've peeked at those two urls above and couldn't see anything suspicious there: on my end, they're just completely blank webpages, without scripts or anything else for that matter – at most, they load a favicon, and the favicon's size is so small that I don't think it could contain anything funky.

I've also tried loading resourceguruapp.com, but perhaps unsurprisingly as you warned about it being sporadic, I couldn't see any ads there either.

👍 for further debugging when/if you see this again, it'll be interesting to look at the stack traces of those network requests that are loading ads to pinpoint where they're coming from!

Without more data to inspect – and without being sure this is related to the Buffer Extension – I'll close this issue for now, but I'm looking forward to anything else that might shed some light on what you were observing, so please reopen/comment when you learn more!
